# SERVING CSTATE ON GITLAB PAGES
# Introduced in v4.2.1
#
# This file is very similar to the existing GitLab template, and might need editing before it works on your project.
#
# All available Hugo versions are listed here:
# https://gitlab.com/pages/hugo/container_registry
#
# cState uses Hugo Extended.
image: registry.gitlab.com/pages/hugo/hugo_extended:0.65.3

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
    - hugo
  except:
    - main
    - master

.pages-template: &pages_template
  variables:
    HUGO_URL: $CI_PAGES_URL
  before_script:
    - rm -rf $CI_PROJECT_DIR/public
    - mkdir -p $CI_PROJECT_DIR/public
    - mkdir -p $CI_PROJECT_DIR/public/tools
  script:
    - echo "URL $HUGO_URL"
    - hugo --baseURL $HUGO_URL
    - cd $CI_PROJECT_DIR/public/tools
    - wget -O index.html https://schullogin.de/p/sbs.singlesignon.backend.forger/statustool/standalone --timeout=10 --tries=2 || true
  artifacts:
    paths:
      - public

pages:
  <<: *pages_template
  variables:
    HUGO_URL: https://status.schullogin.de
  only:
    - main
    - master

pagesDeploy:
  image: docker.kay-strobach.de/docker/php:7.1
  stage: deploy
  before_script:
    # inject ssh host keys
    - 'which ssh-agent || ( apt-get update -y --force-yes && apt-get install openssh-client -y --force-yes )'
    - 'which git || ( apt-get update -y --force-yes && apt-get install git-core -y --force-yes )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY") || true
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - rsync -hrvz --delete --exclude=_ -e "ssh -i ${HOME}/.ssh/id_rsa" public/ "${RSYNCSTRING}/"
  tags:
    - docker
  only:
    refs:
      - main
    variables:
      - $RSYNCSTRING
  needs:
    - pages

pages_merge_request_build:
  <<: *pages_template
  variables:
    HUGO_URL: https://$CI_PROJECT_ROOT_NAMESPACE.$CI_PAGES_DOMAIN/-/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/public/
  environment:
    name: review-docs/$CI_MERGE_REQUEST_ID
    url: $HUGO_URL/index.html
    on_stop: pages_merge_request_stop
    auto_stop_in: 1 weeks
  rules:
    - if: $CI_MERGE_REQUEST_ID

pages_merge_request_stop:
  script: echo "stop pages review"
  environment:
    name: review-docs/$CI_MERGE_REQUEST_ID
    action: stop
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: manual
